DROP DATEBASE IF EXISTS yetycave;
CREATE DATEBASE yetycave
DEFAULT CHARACTER SET utf8
DEFAULT COLLATE utf8_general_ci

USE yetycave;

CREATE TABLE categories (
    id INT(11) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name CHAR(15) NOT NULL,
    code CHAR(15) NOT NULL
);

CREATE TABLE lots (
    id INT(11) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    dt_add DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    category_id INT(11) UNSIGNED NOT NULL,
    user_id INT(11) UNSIGNED NOT NULL,
    title CHAR(70) NOT NULL,
    description TEXT NOT NULL,
    image CHAR(128) NOT NULL,
    cost DECIMAL NOT NULL,
    dt_end DATETIME NOT NULL,
    step INT(5) UNSIGNED NOT NULL,
    winner_id INT(5),
    FOREIGN KEY (user_id) REFERENCES users(id),
    FOREIGN KEY (winner_id) REFERENCES users(id),
    FOREIGN KEY (category_id) REFERENCES categories(id),
    FULLTEXT (title, description)
);

CREATE TABLE users (
    id INT(11) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    dt_add DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    email CHAR(60) NOT NULL UNIQUE,
    name CHAR(100) NOT NULL,
    password CHAR(60) NOT NULL UNIQUE,
    telephone VARCHAR(25) NOT NULL
);

CREATE TABLE rates (
    id INT(11) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    dt_add DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    cost_rate INT(11) UNSIGNED NOT NULL,
    user_id INT(11) UNSIGNED NOT NULL,
    lot_id INT(11) UNSIGNED NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users(id),
    FOREIGN KEY (lot_id) REFERENCES lots(id)
);
